//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Il codice sorgente è stato generato automaticamente da Microsoft.VSDesigner, versione 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace exportDPSonline.fckLogin {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Farmaclick2010001FCKLoginSoapBinding", Namespace="http://farmaclick.infarma.it/Farmaclick2010001FCKLogin")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(ErogazioneServiziBean))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(ServiziBean))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(FornitoreBean))]
    public partial class farmaclick2010001Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback FCKLoginOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public farmaclick2010001Service() {
            this.Url = global::exportDPSonline.Properties.Settings.Default.exportDPSonline_fckLogin_farmaclick2010001Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event FCKLoginCompletedEventHandler FCKLoginCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://api.farmaclick.infarma.it", ResponseNamespace="http://farmaclick.infarma.it/Farmaclick2010001FCKLogin")]
        [return: System.Xml.Serialization.SoapElementAttribute("FCKLoginReturn")]
        public LoginOutputBean FCKLogin(LoginInputBean inBean) {
            object[] results = this.Invoke("FCKLogin", new object[] {
                        inBean});
            return ((LoginOutputBean)(results[0]));
        }
        
        /// <remarks/>
        public void FCKLoginAsync(LoginInputBean inBean) {
            this.FCKLoginAsync(inBean, null);
        }
        
        /// <remarks/>
        public void FCKLoginAsync(LoginInputBean inBean, object userState) {
            if ((this.FCKLoginOperationCompleted == null)) {
                this.FCKLoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFCKLoginOperationCompleted);
            }
            this.InvokeAsync("FCKLogin", new object[] {
                        inBean}, this.FCKLoginOperationCompleted, userState);
        }
        
        private void OnFCKLoginOperationCompleted(object arg) {
            if ((this.FCKLoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FCKLoginCompleted(this, new FCKLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:BeanService")]
    public partial class LoginInputBean {
        
        private string nomeTerminaleField;
        
        private string passwordField;
        
        private string passwordSHField;
        
        private string userNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nomeTerminale {
            get {
                return this.nomeTerminaleField;
            }
            set {
                this.nomeTerminaleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string passwordSH {
            get {
                return this.passwordSHField;
            }
            set {
                this.passwordSHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:BeanService")]
    public partial class ErogazioneServiziBean {
        
        private int giornoField;
        
        private System.Nullable<System.DateTime> oraFineField;
        
        private System.Nullable<System.DateTime> oraInizioField;
        
        /// <remarks/>
        public int giorno {
            get {
                return this.giornoField;
            }
            set {
                this.giornoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> oraFine {
            get {
                return this.oraFineField;
            }
            set {
                this.oraFineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> oraInizio {
            get {
                return this.oraInizioField;
            }
            set {
                this.oraInizioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:BeanService")]
    public partial class ServiziBean {
        
        private int abilitatoField;
        
        private ErogazioneServiziBean[] arrayErogazioneServiziField;
        
        private string codiceServizioField;
        
        private string livelloAPIField;
        
        private string url1Field;
        
        private string url2Field;
        
        /// <remarks/>
        public int abilitato {
            get {
                return this.abilitatoField;
            }
            set {
                this.abilitatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public ErogazioneServiziBean[] arrayErogazioneServizi {
            get {
                return this.arrayErogazioneServiziField;
            }
            set {
                this.arrayErogazioneServiziField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codiceServizio {
            get {
                return this.codiceServizioField;
            }
            set {
                this.codiceServizioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string livelloAPI {
            get {
                return this.livelloAPIField;
            }
            set {
                this.livelloAPIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string url1 {
            get {
                return this.url1Field;
            }
            set {
                this.url1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string url2 {
            get {
                return this.url2Field;
            }
            set {
                this.url2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:BeanService")]
    public partial class FornitoreBean {
        
        private string iDSessioneField;
        
        private ServiziBean[] arrayServiziField;
        
        private string codiceField;
        
        private string codiceSitoLogisticoField;
        
        private string descrizioneBreveField;
        
        private System.Nullable<System.DateTime> fineFermoMacchinaField;
        
        private System.Nullable<System.DateTime> inizioFermoMacchinaField;
        
        private string livelloAPIField;
        
        private System.Nullable<System.DateTime> scadenzaSessioneField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string IDSessione {
            get {
                return this.iDSessioneField;
            }
            set {
                this.iDSessioneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public ServiziBean[] arrayServizi {
            get {
                return this.arrayServiziField;
            }
            set {
                this.arrayServiziField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codice {
            get {
                return this.codiceField;
            }
            set {
                this.codiceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codiceSitoLogistico {
            get {
                return this.codiceSitoLogisticoField;
            }
            set {
                this.codiceSitoLogisticoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string descrizioneBreve {
            get {
                return this.descrizioneBreveField;
            }
            set {
                this.descrizioneBreveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> fineFermoMacchina {
            get {
                return this.fineFermoMacchinaField;
            }
            set {
                this.fineFermoMacchinaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> inizioFermoMacchina {
            get {
                return this.inizioFermoMacchinaField;
            }
            set {
                this.inizioFermoMacchinaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string livelloAPI {
            get {
                return this.livelloAPIField;
            }
            set {
                this.livelloAPIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> scadenzaSessione {
            get {
                return this.scadenzaSessioneField;
            }
            set {
                this.scadenzaSessioneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:BeanService")]
    public partial class LoginOutputBean {
        
        private FornitoreBean[] arrayFornitoriField;
        
        private int esitoServizioField;
        
        private string newPasswordField;
        
        private System.Nullable<System.DateTime> serverTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public FornitoreBean[] arrayFornitori {
            get {
                return this.arrayFornitoriField;
            }
            set {
                this.arrayFornitoriField = value;
            }
        }
        
        /// <remarks/>
        public int esitoServizio {
            get {
                return this.esitoServizioField;
            }
            set {
                this.esitoServizioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string newPassword {
            get {
                return this.newPasswordField;
            }
            set {
                this.newPasswordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> serverTime {
            get {
                return this.serverTimeField;
            }
            set {
                this.serverTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void FCKLoginCompletedEventHandler(object sender, FCKLoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FCKLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FCKLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LoginOutputBean Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LoginOutputBean)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591