//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Il codice sorgente è stato generato automaticamente da Microsoft.VSDesigner, versione 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace exportDPSonline.FCKInfo {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Farmaclick2010001FCKInfoComSoapBinding", Namespace="http://farmaclick.infarma.it/Farmaclick2010001FCKInfoCom")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(OfferteOutputBean))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(FatturazioneOutputBean))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(ConsegnaDifferitaOutputBean))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(ConsegnaOutputBean))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(CampagnaPreconfezionataOutputBean))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(ArticoloInfoOutputBean))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(ArticoloInputBean))]
    public partial class farmaclick2010001Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback FCKInfoComOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public farmaclick2010001Service() {
            this.Url = global::exportDPSonline.Properties.Settings.Default.exportDPSonline_FCKInfo_farmaclick2010001Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event FCKInfoComCompletedEventHandler FCKInfoComCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://api.farmaclick.infarma.it/", ResponseNamespace="http://farmaclick.infarma.it/Farmaclick2010001FCKInfoCom")]
        [return: System.Xml.Serialization.SoapElementAttribute("FCKInfoComReturn")]
        public InfoComOutputBean FCKInfoCom(InfoComInputBean inBean) {
            object[] results = this.Invoke("FCKInfoCom", new object[] {
                        inBean});
            return ((InfoComOutputBean)(results[0]));
        }
        
        /// <remarks/>
        public void FCKInfoComAsync(InfoComInputBean inBean) {
            this.FCKInfoComAsync(inBean, null);
        }
        
        /// <remarks/>
        public void FCKInfoComAsync(InfoComInputBean inBean, object userState) {
            if ((this.FCKInfoComOperationCompleted == null)) {
                this.FCKInfoComOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFCKInfoComOperationCompleted);
            }
            this.InvokeAsync("FCKInfoCom", new object[] {
                        inBean}, this.FCKInfoComOperationCompleted, userState);
        }
        
        private void OnFCKInfoComOperationCompleted(object arg) {
            if ((this.FCKInfoComCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FCKInfoComCompleted(this, new FCKInfoComCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:BeanService")]
    public partial class InfoComInputBean {
        
        private string iDSessioneField;
        
        private ArticoloInputBean[] arrayArticoliInputField;
        
        private string codiceFornitoreField;
        
        private string codiceTipoOrdineField;
        
        private bool descrizioneArticoliField;
        
        private bool descrizioneMotivazioneMancanzaField;
        
        private bool indicazioneOfferteField;
        
        private bool indicazioneScontiField;
        
        private string riferimentoOrdineFarmaciaField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string IDSessione {
            get {
                return this.iDSessioneField;
            }
            set {
                this.iDSessioneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public ArticoloInputBean[] arrayArticoliInput {
            get {
                return this.arrayArticoliInputField;
            }
            set {
                this.arrayArticoliInputField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codiceFornitore {
            get {
                return this.codiceFornitoreField;
            }
            set {
                this.codiceFornitoreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codiceTipoOrdine {
            get {
                return this.codiceTipoOrdineField;
            }
            set {
                this.codiceTipoOrdineField = value;
            }
        }
        
        /// <remarks/>
        public bool descrizioneArticoli {
            get {
                return this.descrizioneArticoliField;
            }
            set {
                this.descrizioneArticoliField = value;
            }
        }
        
        /// <remarks/>
        public bool descrizioneMotivazioneMancanza {
            get {
                return this.descrizioneMotivazioneMancanzaField;
            }
            set {
                this.descrizioneMotivazioneMancanzaField = value;
            }
        }
        
        /// <remarks/>
        public bool indicazioneOfferte {
            get {
                return this.indicazioneOfferteField;
            }
            set {
                this.indicazioneOfferteField = value;
            }
        }
        
        /// <remarks/>
        public bool indicazioneSconti {
            get {
                return this.indicazioneScontiField;
            }
            set {
                this.indicazioneScontiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string riferimentoOrdineFarmacia {
            get {
                return this.riferimentoOrdineFarmaciaField;
            }
            set {
                this.riferimentoOrdineFarmaciaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:BeanService")]
    public partial class ArticoloInputBean {
        
        private string codiceProdottoField;
        
        private bool prenotazioneField;
        
        private int quantitaRichiestaField;
        
        private string rifRigaField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codiceProdotto {
            get {
                return this.codiceProdottoField;
            }
            set {
                this.codiceProdottoField = value;
            }
        }
        
        /// <remarks/>
        public bool prenotazione {
            get {
                return this.prenotazioneField;
            }
            set {
                this.prenotazioneField = value;
            }
        }
        
        /// <remarks/>
        public int quantitaRichiesta {
            get {
                return this.quantitaRichiestaField;
            }
            set {
                this.quantitaRichiestaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string rifRiga {
            get {
                return this.rifRigaField;
            }
            set {
                this.rifRigaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:BeanService")]
    public partial class OfferteOutputBean {
        
        private string codiceAccorpatoreCondizioneField;
        
        private string codiceOmaggioAlternativoField;
        
        private System.Nullable<System.DateTime> dataFineValiditaField;
        
        private string descrizioneOmaggioAlternativoField;
        
        private double importoNettoRigaField;
        
        private int limitePezziAField;
        
        private int limitePezziDaField;
        
        private string modalitaPagamentoField;
        
        private int numeroMinimoPezziField;
        
        private bool offertaApplicataField;
        
        private int quantitaAssegnataField;
        
        private int quantitaMassimaOrdinabileField;
        
        private int quantitaOmaggioField;
        
        private int quantitaOmaggioAlternativoField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codiceAccorpatoreCondizione {
            get {
                return this.codiceAccorpatoreCondizioneField;
            }
            set {
                this.codiceAccorpatoreCondizioneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codiceOmaggioAlternativo {
            get {
                return this.codiceOmaggioAlternativoField;
            }
            set {
                this.codiceOmaggioAlternativoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> dataFineValidita {
            get {
                return this.dataFineValiditaField;
            }
            set {
                this.dataFineValiditaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string descrizioneOmaggioAlternativo {
            get {
                return this.descrizioneOmaggioAlternativoField;
            }
            set {
                this.descrizioneOmaggioAlternativoField = value;
            }
        }
        
        /// <remarks/>
        public double importoNettoRiga {
            get {
                return this.importoNettoRigaField;
            }
            set {
                this.importoNettoRigaField = value;
            }
        }
        
        /// <remarks/>
        public int limitePezziA {
            get {
                return this.limitePezziAField;
            }
            set {
                this.limitePezziAField = value;
            }
        }
        
        /// <remarks/>
        public int limitePezziDa {
            get {
                return this.limitePezziDaField;
            }
            set {
                this.limitePezziDaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string modalitaPagamento {
            get {
                return this.modalitaPagamentoField;
            }
            set {
                this.modalitaPagamentoField = value;
            }
        }
        
        /// <remarks/>
        public int numeroMinimoPezzi {
            get {
                return this.numeroMinimoPezziField;
            }
            set {
                this.numeroMinimoPezziField = value;
            }
        }
        
        /// <remarks/>
        public bool offertaApplicata {
            get {
                return this.offertaApplicataField;
            }
            set {
                this.offertaApplicataField = value;
            }
        }
        
        /// <remarks/>
        public int quantitaAssegnata {
            get {
                return this.quantitaAssegnataField;
            }
            set {
                this.quantitaAssegnataField = value;
            }
        }
        
        /// <remarks/>
        public int quantitaMassimaOrdinabile {
            get {
                return this.quantitaMassimaOrdinabileField;
            }
            set {
                this.quantitaMassimaOrdinabileField = value;
            }
        }
        
        /// <remarks/>
        public int quantitaOmaggio {
            get {
                return this.quantitaOmaggioField;
            }
            set {
                this.quantitaOmaggioField = value;
            }
        }
        
        /// <remarks/>
        public int quantitaOmaggioAlternativo {
            get {
                return this.quantitaOmaggioAlternativoField;
            }
            set {
                this.quantitaOmaggioAlternativoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:BeanService")]
    public partial class FatturazioneOutputBean {
        
        private string codiceFornitoreField;
        
        private int quantitaFatturataField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codiceFornitore {
            get {
                return this.codiceFornitoreField;
            }
            set {
                this.codiceFornitoreField = value;
            }
        }
        
        /// <remarks/>
        public int quantitaFatturata {
            get {
                return this.quantitaFatturataField;
            }
            set {
                this.quantitaFatturataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:BeanService")]
    public partial class ConsegnaDifferitaOutputBean {
        
        private string codiceConsegnaField;
        
        private string codiceFornitoreField;
        
        private System.Nullable<System.DateTime> dataConsegnaField;
        
        private System.Nullable<System.DateTime> dataFineValiditaField;
        
        private int disponibilitaProdottoField;
        
        private string noteField;
        
        private int quantitaField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codiceConsegna {
            get {
                return this.codiceConsegnaField;
            }
            set {
                this.codiceConsegnaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codiceFornitore {
            get {
                return this.codiceFornitoreField;
            }
            set {
                this.codiceFornitoreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> dataConsegna {
            get {
                return this.dataConsegnaField;
            }
            set {
                this.dataConsegnaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> dataFineValidita {
            get {
                return this.dataFineValiditaField;
            }
            set {
                this.dataFineValiditaField = value;
            }
        }
        
        /// <remarks/>
        public int disponibilitaProdotto {
            get {
                return this.disponibilitaProdottoField;
            }
            set {
                this.disponibilitaProdottoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string note {
            get {
                return this.noteField;
            }
            set {
                this.noteField = value;
            }
        }
        
        /// <remarks/>
        public int quantita {
            get {
                return this.quantitaField;
            }
            set {
                this.quantitaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:BeanService")]
    public partial class ConsegnaOutputBean {
        
        private string codiceCorriereField;
        
        private string codiceFornitoreField;
        
        private System.Nullable<System.DateTime> dataConsegnaField;
        
        private int quantitaConsegnataField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codiceCorriere {
            get {
                return this.codiceCorriereField;
            }
            set {
                this.codiceCorriereField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codiceFornitore {
            get {
                return this.codiceFornitoreField;
            }
            set {
                this.codiceFornitoreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> dataConsegna {
            get {
                return this.dataConsegnaField;
            }
            set {
                this.dataConsegnaField = value;
            }
        }
        
        /// <remarks/>
        public int quantitaConsegnata {
            get {
                return this.quantitaConsegnataField;
            }
            set {
                this.quantitaConsegnataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:BeanService")]
    public partial class CampagnaPreconfezionataOutputBean {
        
        private string codiceTipoOrdineField;
        
        private string descrizioneField;
        
        private string linkField;
        
        private bool offertaApertaField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codiceTipoOrdine {
            get {
                return this.codiceTipoOrdineField;
            }
            set {
                this.codiceTipoOrdineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string descrizione {
            get {
                return this.descrizioneField;
            }
            set {
                this.descrizioneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string link {
            get {
                return this.linkField;
            }
            set {
                this.linkField = value;
            }
        }
        
        /// <remarks/>
        public bool offertaAperta {
            get {
                return this.offertaApertaField;
            }
            set {
                this.offertaApertaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:BeanService")]
    public partial class ArticoloInfoOutputBean {
        
        private CampagnaPreconfezionataOutputBean[] arrayCampagnePField;
        
        private ConsegnaOutputBean[] arrayConsegnaField;
        
        private ConsegnaDifferitaOutputBean[] arrayConsegnaDifferitaField;
        
        private FatturazioneOutputBean[] arrayFatturazioneField;
        
        private OfferteOutputBean[] arrayOfferteField;
        
        private string codiceCampComField;
        
        private string codiceMancanzaField;
        
        private string codiceOmaggioAlternativoField;
        
        private string codiceProdottoField;
        
        private string codiceProdottoSostituitoField;
        
        private bool consegnaRitardataField;
        
        private System.Nullable<System.DateTime> dataPrevistaConsegnaPrenotazioneField;
        
        private System.Nullable<System.DateTime> dataPrevistaDisponibilitaField;
        
        private string descrizioneMancanzaField;
        
        private string descrizioneOmaggioAlternativoField;
        
        private string descrizioneProdottoField;
        
        private string descrizioneProdottoSostituitoField;
        
        private double importoNettoRigaField;
        
        private int ivaField;
        
        private string linkField;
        
        private bool multiploField;
        
        private string noteField;
        
        private bool prenotabileField;
        
        private double prezzoConsigliatoField;
        
        private double prezzoNettoUnitarioField;
        
        private double prezzopublicoField;
        
        private int quantitaConfezioneField;
        
        private int quantitaConsegnataField;
        
        private int quantitaMancanteField;
        
        private int quantitaMinimaField;
        
        private int quantitaOmaggioField;
        
        private int quantitaOmaggioAlternativoField;
        
        private int quantitaRichiestaField;
        
        private string rifRigaField;
        
        private double scontoCampCom1Field;
        
        private double scontoCampCom2Field;
        
        private double scontoLordoField;
        
        private double scontoNettoField;
        
        private bool trattatoField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public CampagnaPreconfezionataOutputBean[] arrayCampagneP {
            get {
                return this.arrayCampagnePField;
            }
            set {
                this.arrayCampagnePField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public ConsegnaOutputBean[] arrayConsegna {
            get {
                return this.arrayConsegnaField;
            }
            set {
                this.arrayConsegnaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public ConsegnaDifferitaOutputBean[] arrayConsegnaDifferita {
            get {
                return this.arrayConsegnaDifferitaField;
            }
            set {
                this.arrayConsegnaDifferitaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public FatturazioneOutputBean[] arrayFatturazione {
            get {
                return this.arrayFatturazioneField;
            }
            set {
                this.arrayFatturazioneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public OfferteOutputBean[] arrayOfferte {
            get {
                return this.arrayOfferteField;
            }
            set {
                this.arrayOfferteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codiceCampCom {
            get {
                return this.codiceCampComField;
            }
            set {
                this.codiceCampComField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codiceMancanza {
            get {
                return this.codiceMancanzaField;
            }
            set {
                this.codiceMancanzaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codiceOmaggioAlternativo {
            get {
                return this.codiceOmaggioAlternativoField;
            }
            set {
                this.codiceOmaggioAlternativoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codiceProdotto {
            get {
                return this.codiceProdottoField;
            }
            set {
                this.codiceProdottoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codiceProdottoSostituito {
            get {
                return this.codiceProdottoSostituitoField;
            }
            set {
                this.codiceProdottoSostituitoField = value;
            }
        }
        
        /// <remarks/>
        public bool consegnaRitardata {
            get {
                return this.consegnaRitardataField;
            }
            set {
                this.consegnaRitardataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> dataPrevistaConsegnaPrenotazione {
            get {
                return this.dataPrevistaConsegnaPrenotazioneField;
            }
            set {
                this.dataPrevistaConsegnaPrenotazioneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> dataPrevistaDisponibilita {
            get {
                return this.dataPrevistaDisponibilitaField;
            }
            set {
                this.dataPrevistaDisponibilitaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string descrizioneMancanza {
            get {
                return this.descrizioneMancanzaField;
            }
            set {
                this.descrizioneMancanzaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string descrizioneOmaggioAlternativo {
            get {
                return this.descrizioneOmaggioAlternativoField;
            }
            set {
                this.descrizioneOmaggioAlternativoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string descrizioneProdotto {
            get {
                return this.descrizioneProdottoField;
            }
            set {
                this.descrizioneProdottoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string descrizioneProdottoSostituito {
            get {
                return this.descrizioneProdottoSostituitoField;
            }
            set {
                this.descrizioneProdottoSostituitoField = value;
            }
        }
        
        /// <remarks/>
        public double importoNettoRiga {
            get {
                return this.importoNettoRigaField;
            }
            set {
                this.importoNettoRigaField = value;
            }
        }
        
        /// <remarks/>
        public int iva {
            get {
                return this.ivaField;
            }
            set {
                this.ivaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string link {
            get {
                return this.linkField;
            }
            set {
                this.linkField = value;
            }
        }
        
        /// <remarks/>
        public bool multiplo {
            get {
                return this.multiploField;
            }
            set {
                this.multiploField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string note {
            get {
                return this.noteField;
            }
            set {
                this.noteField = value;
            }
        }
        
        /// <remarks/>
        public bool prenotabile {
            get {
                return this.prenotabileField;
            }
            set {
                this.prenotabileField = value;
            }
        }
        
        /// <remarks/>
        public double prezzoConsigliato {
            get {
                return this.prezzoConsigliatoField;
            }
            set {
                this.prezzoConsigliatoField = value;
            }
        }
        
        /// <remarks/>
        public double prezzoNettoUnitario {
            get {
                return this.prezzoNettoUnitarioField;
            }
            set {
                this.prezzoNettoUnitarioField = value;
            }
        }
        
        /// <remarks/>
        public double prezzopublico {
            get {
                return this.prezzopublicoField;
            }
            set {
                this.prezzopublicoField = value;
            }
        }
        
        /// <remarks/>
        public int quantitaConfezione {
            get {
                return this.quantitaConfezioneField;
            }
            set {
                this.quantitaConfezioneField = value;
            }
        }
        
        /// <remarks/>
        public int quantitaConsegnata {
            get {
                return this.quantitaConsegnataField;
            }
            set {
                this.quantitaConsegnataField = value;
            }
        }
        
        /// <remarks/>
        public int quantitaMancante {
            get {
                return this.quantitaMancanteField;
            }
            set {
                this.quantitaMancanteField = value;
            }
        }
        
        /// <remarks/>
        public int quantitaMinima {
            get {
                return this.quantitaMinimaField;
            }
            set {
                this.quantitaMinimaField = value;
            }
        }
        
        /// <remarks/>
        public int quantitaOmaggio {
            get {
                return this.quantitaOmaggioField;
            }
            set {
                this.quantitaOmaggioField = value;
            }
        }
        
        /// <remarks/>
        public int quantitaOmaggioAlternativo {
            get {
                return this.quantitaOmaggioAlternativoField;
            }
            set {
                this.quantitaOmaggioAlternativoField = value;
            }
        }
        
        /// <remarks/>
        public int quantitaRichiesta {
            get {
                return this.quantitaRichiestaField;
            }
            set {
                this.quantitaRichiestaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string rifRiga {
            get {
                return this.rifRigaField;
            }
            set {
                this.rifRigaField = value;
            }
        }
        
        /// <remarks/>
        public double scontoCampCom1 {
            get {
                return this.scontoCampCom1Field;
            }
            set {
                this.scontoCampCom1Field = value;
            }
        }
        
        /// <remarks/>
        public double scontoCampCom2 {
            get {
                return this.scontoCampCom2Field;
            }
            set {
                this.scontoCampCom2Field = value;
            }
        }
        
        /// <remarks/>
        public double scontoLordo {
            get {
                return this.scontoLordoField;
            }
            set {
                this.scontoLordoField = value;
            }
        }
        
        /// <remarks/>
        public double scontoNetto {
            get {
                return this.scontoNettoField;
            }
            set {
                this.scontoNettoField = value;
            }
        }
        
        /// <remarks/>
        public bool trattato {
            get {
                return this.trattatoField;
            }
            set {
                this.trattatoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:BeanService")]
    public partial class InfoComOutputBean {
        
        private ArticoloInfoOutputBean[] arrayArticoliField;
        
        private int delayProsRichiestaField;
        
        private int esitoServizioField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public ArticoloInfoOutputBean[] arrayArticoli {
            get {
                return this.arrayArticoliField;
            }
            set {
                this.arrayArticoliField = value;
            }
        }
        
        /// <remarks/>
        public int delayProsRichiesta {
            get {
                return this.delayProsRichiestaField;
            }
            set {
                this.delayProsRichiestaField = value;
            }
        }
        
        /// <remarks/>
        public int esitoServizio {
            get {
                return this.esitoServizioField;
            }
            set {
                this.esitoServizioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void FCKInfoComCompletedEventHandler(object sender, FCKInfoComCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FCKInfoComCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FCKInfoComCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public InfoComOutputBean Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((InfoComOutputBean)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591